set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_A_tri_io[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[0]}]

set_property PACKAGE_PIN J20 [get_ports {GPIO_A_tri_io[0]}]
set_property PACKAGE_PIN K21 [get_ports {GPIO_A_tri_io[1]}]

set_property PACKAGE_PIN J16 [get_ports {GPIO_A_tri_io[2]}]
set_property PACKAGE_PIN J17 [get_ports {GPIO_A_tri_io[3]}]

set_property PACKAGE_PIN G20 [get_ports {GPIO_A_tri_io[4]}]
set_property PACKAGE_PIN G21 [get_ports {GPIO_A_tri_io[5]}]

set_property PACKAGE_PIN G15 [get_ports {GPIO_A_tri_io[6]}]
set_property PACKAGE_PIN G16 [get_ports {GPIO_A_tri_io[7]}]

set_property PACKAGE_PIN G19 [get_ports {GPIO_A_tri_io[8]}]
set_property PACKAGE_PIN F19 [get_ports {GPIO_A_tri_io[9]}]

set_property PACKAGE_PIN E19 [get_ports {GPIO_A_tri_io[10]}]
set_property PACKAGE_PIN E20 [get_ports {GPIO_A_tri_io[11]}]

set_property PACKAGE_PIN D22 [get_ports {GPIO_A_tri_io[12]}]
set_property PACKAGE_PIN C22 [get_ports {GPIO_A_tri_io[13]}]

set_property PACKAGE_PIN A18 [get_ports {GPIO_A_tri_io[14]}]
set_property PACKAGE_PIN A19 [get_ports {GPIO_A_tri_io[15]}]

set_property PACKAGE_PIN M19 [get_ports {GPIO_A_tri_io[16]}]
set_property PACKAGE_PIN M20 [get_ports {GPIO_A_tri_io[17]}]

set_property PACKAGE_PIN P17 [get_ports {GPIO_A_tri_io[18]}]
set_property PACKAGE_PIN P18 [get_ports {GPIO_A_tri_io[19]}]

set_property PACKAGE_PIN N22 [get_ports {GPIO_A_tri_io[20]}]
set_property PACKAGE_PIN P22 [get_ports {GPIO_A_tri_io[21]}]

set_property PACKAGE_PIN M21 [get_ports {GPIO_A_tri_io[22]}]
set_property PACKAGE_PIN M22 [get_ports {GPIO_A_tri_io[23]}]

set_property PACKAGE_PIN J21 [get_ports {GPIO_A_tri_io[24]}]
set_property PACKAGE_PIN J22 [get_ports {GPIO_A_tri_io[25]}]

set_property PACKAGE_PIN T16 [get_ports {GPIO_A_tri_io[26]}]
set_property PACKAGE_PIN T17 [get_ports {GPIO_A_tri_io[27]}]

set_property PACKAGE_PIN P20 [get_ports {GPIO_A_tri_io[28]}]
set_property PACKAGE_PIN P21 [get_ports {GPIO_A_tri_io[29]}]

set_property PACKAGE_PIN N17 [get_ports {GPIO_A_tri_io[30]}]
set_property PACKAGE_PIN N18 [get_ports {GPIO_A_tri_io[31]}]

set_property PACKAGE_PIN B16 [get_ports {GPIO_B_tri_io[0]}]
set_property PACKAGE_PIN B17 [get_ports {GPIO_B_tri_io[1]}]

set_property PACKAGE_PIN A16 [get_ports {GPIO_B_tri_io[2]}]
set_property PACKAGE_PIN A17 [get_ports {GPIO_B_tri_io[3]}]

set_property PACKAGE_PIN B21 [get_ports {GPIO_B_tri_io[4]}]
set_property PACKAGE_PIN B22 [get_ports {GPIO_B_tri_io[5]}]

set_property PACKAGE_PIN L21 [get_ports {GPIO_B_tri_io[6]}]
set_property PACKAGE_PIN L22 [get_ports {GPIO_B_tri_io[7]}]

set_property PACKAGE_PIN R19 [get_ports {GPIO_B_tri_io[8]}]
set_property PACKAGE_PIN T19 [get_ports {GPIO_B_tri_io[9]}]

set_property PACKAGE_PIN K19 [get_ports {GPIO_B_tri_io[10]}]
set_property PACKAGE_PIN K20 [get_ports {GPIO_B_tri_io[11]}]

set_property PACKAGE_PIN E21 [get_ports {GPIO_B_tri_io[12]}]
set_property PACKAGE_PIN D21 [get_ports {GPIO_B_tri_io[13]}]

set_property PACKAGE_PIN F22 [get_ports {GPIO_B_tri_io[14]}]
set_property PACKAGE_PIN G22 [get_ports {GPIO_B_tri_io[15]}]

set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {GPIO_B_tri_io[16]}]
set_property PACKAGE_PIN M16 [get_ports {GPIO_B_tri_io[31]}]
set_property PACKAGE_PIN J18 [get_ports {GPIO_B_tri_io[30]}]
set_property PACKAGE_PIN K18 [get_ports {GPIO_B_tri_io[29]}]
set_property PACKAGE_PIN L18 [get_ports {GPIO_B_tri_io[28]}]
set_property PACKAGE_PIN L19 [get_ports {GPIO_B_tri_io[27]}]
set_property PACKAGE_PIN N19 [get_ports {GPIO_B_tri_io[26]}]
set_property PACKAGE_PIN N20 [get_ports {GPIO_B_tri_io[25]}]
set_property PACKAGE_PIN R20 [get_ports {GPIO_B_tri_io[24]}]
set_property PACKAGE_PIN R21 [get_ports {GPIO_B_tri_io[23]}]
set_property PACKAGE_PIN N15 [get_ports {GPIO_B_tri_io[22]}]
set_property PACKAGE_PIN P15 [get_ports {GPIO_B_tri_io[21]}]
set_property PACKAGE_PIN R18 [get_ports {GPIO_B_tri_io[20]}]
set_property PACKAGE_PIN T18 [get_ports {GPIO_B_tri_io[19]}]
set_property PACKAGE_PIN P16 [get_ports {GPIO_B_tri_io[18]}]
set_property PACKAGE_PIN R16 [get_ports {GPIO_B_tri_io[17]}]
set_property PACKAGE_PIN R15 [get_ports {GPIO_B_tri_io[16]}]
